# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/resources'
        bogportalen.storage:
            adapter: 'ftp'
            options:
                host: ''
                username: ''
                password: ''
                root: 'Public'
                ssl: false
        rbdigital.storage:
            adapter: 'ftp'
            options:
                host: ''
                username: ''
                password: ''
                root: 'Marc/OCLC/Subscription'
                ssl: false
