# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        # Note that Ruflin\Elastica requires a trailing slash
        default: { url: '%env(ELASTIC_URL)%/' }
    indexes:
        app:
            index_name: app_%kernel.environment%
            types:
                search:
                    properties:
                        isIdentifier: {type:  keyword}
                        isType: {type:  keyword}
                        imageUrl: ~
                        imageFormat: {type:  keyword}
                        width: {type: integer}
                        height: {type: integer}
                    persistence:
                        driver: orm
                        model: App\Entity\Search
                        provider: ~
                        finder: ~
                        repository: App\Repository\SearchRepository
                        elastica_to_model_transformer:
                            ignore_missing: true
