framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            async_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: high
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            search-queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: search

            cover-store-queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: coverstore

            cover-store-auto-queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: coverstoreauto

            background-queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: background

            #failed: 'doctrine://default?queue_name=failed'

        routing:
            'App\Message\SearchMessage': search-queue
            'App\Message\DeleteMessage': background-queue
            'App\Message\SearchNoHitsMessage': background-queue
            'App\Message\VendorImageMessage': cover-store-queue
            'App\Message\CoverStoreMessage': cover-store-queue
            'App\Message\CoverUserUploadMessage': cover-store-queue
            'App\Message\CoverStoreAutoMessage': cover-store-auto-queue
