services:
  monolog.elastica.client:
    class: Elastica\Client
    arguments:
      # Note that Ruflin\Elastica used by monolog requires a trailing slash
      $config: { url: '%env(ELASTIC_URL)%/' }

monolog:
  #
  # Set new logger to log statistics information to ES.
  #
  channels: ["statistics"]
  handlers:
    statistics:
      type: elasticsearch
      elasticsearch:
        id: monolog.elastica.client
      index: '%env(ELASTIC_STATS_INDEX)%'
      channels: ["statistics"]
