# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        filesystem_adapter:
            local:
                directory: '%kernel.cache_dir%/flysystem'
        bogportalen_ftp:
            ftp:
                host: ''
                username: ''
                password: ''
                root: 'Public'
                ssl: false
        rbdigital_ftp:
            ftp:
                host: ''
                username: ''
                password: ''
                root: 'Marc/OCLC/Subscription'
                ssl: false
    filesystems:
        local:
            adapter: filesystem_adapter
            alias: League\Flysystem\Filesystem

        bogportalen_ftp:
            adapter: bogportalen_ftp

        rbdigital_ftp:
            adapter: rbdigital_ftp
