version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
      #- ENCRYPT=1 # Uncomment to enable database encryption.

  phpfpm:
    image: itkdev/php8.1-fpm
    networks:
      - app
    environment:
      - PHP_XDEBUG_MODE=${PHP_XDEBUG_MODE:-off}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      # - PHP_MAIL=1 # Uncomment to enable mailhog.
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - COMPOSER_VERSION=2
      - PHP_IDE_CONFIG=serverName=localhost
      # Send all container trafik though proxy, useful for testing.
#      - HTTP_PROXY=host.docker.internal:8090
#      - HTTPS_PROXY=host.docker.internal:8090
    depends_on:
      - mariadb
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - '80'
    volumes:
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  redis:
    image: 'redis:6'
    networks:
      - app
    ports:
      - '6379'

  elasticsearch:
    image: elasticsearch:8.5.2
    networks:
      - app
    environment:
      - node.name=es01
      - discovery.type=single-node
      - ELASTIC_PASSWORD="password"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    ports:
      - '9200'
      - '9300'

  rabbit:
    image: rabbitmq:3.9-management
    networks:
      - app
      - frontend
    ports:
      - '15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE='d53f319cd7376f8f840aaf9889f315ab'

volumes:
  esdata:
    driver: local
