---
apiVersion: v1
kind: Pod
metadata:
  name: cover-service-import
  namespace: cover-service
spec:
  imagePullSecrets:
    - name: github-registry
  containers:
  - name: cover-service-import
    image: docker.pkg.github.com/danskernesdigitalebibliotek/ddb-cover-service-importers/cover-service-importers:${APP_VERSION}
    imagePullPolicy: Always
    resources:
      requests:
        memory: "640Mi"
        cpu: "300m"
      limits:
        memory: "640Mi"
        cpu: "500m"
    env:
      - name: APP_DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_DB_USERNAME
      - name: APP_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_DB_PASSWORD
      - name: APP_OPENPLATFORM_ID
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_OPENPLATFORM_ID
      - name: APP_OPENPLATFORM_SECRET
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_OPENPLATFORM_SECRET
      - name: APP_OPENPLATFORM_AGENCY
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_OPENPLATFORM_AGENCY
      - name: APP_DATAWELL_VENDOR_USER
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_DATAWELL_VENDOR_USER
      - name: APP_DATAWELL_VENDOR_PASSWORD
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_DATAWELL_VENDOR_PASSWORD
      - name: APP_CLOUDINARY_ID
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_CLOUDINARY_ID
      - name: APP_CLOUDINARY_SECRET
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_CLOUDINARY_SECRET
      - name: APP_CLOUDINARY_DOMAIN
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_CLOUDINARY_DOMAIN
      - name: APP_THEMOVIEDATABASE_APIKEY
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_THEMOVIEDATABASE_APIKEY
      - name: APP_SECRET
        valueFrom:
          secretKeyRef:
            name: cover-service-import-secret
            key: APP_SECRET
    envFrom:
      - configMapRef:
          name: cover-service-importers-config