---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: cover-service
  name: cover-service-cronjob-bogportal
spec:
  # At 01:00 on every day-of-week from Monday through Saturday.
  schedule: "0 1 * * 1-6"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: docker.pkg.github.com/danskernesdigitalebibliotek/ddb-cover-service-importers/cover-service-importers:${APP_VERSION}
              args:
                - "bin/console"
                - "app:vendor:load"
                - "--no-debug"
                - "--vendor=1"
              env:
                - name: APP_DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_DB_USERNAME
                - name: APP_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_DB_PASSWORD
                - name: APP_OPENPLATFORM_ID
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_OPENPLATFORM_ID
                - name: APP_OPENPLATFORM_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_OPENPLATFORM_SECRET
                - name: APP_OPENPLATFORM_AGENCY
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_OPENPLATFORM_AGENCY
                - name: APP_DATAWELL_VENDOR_USER
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_DATAWELL_VENDOR_USER
                - name: APP_DATAWELL_VENDOR_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_DATAWELL_VENDOR_PASSWORD
                - name: APP_CLOUDINARY_ID
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_CLOUDINARY_ID
                - name: APP_CLOUDINARY_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_CLOUDINARY_SECRET
                - name: APP_CLOUDINARY_DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_CLOUDINARY_DOMAIN
                - name: APP_THEMOVIEDATABASE_APIKEY
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_THEMOVIEDATABASE_APIKEY
                - name: APP_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: cover-service-import-secret
                      key: APP_SECRET
                envFrom:
                  - configMapRef:
                      name: cover-service-importers-config
          restartPolicy: OnFailure