---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-configmap
data:
  APP_DB_SERVER: {{ .Values.app.db.server | quote }}
  APP_DB_PORT: {{ .Values.app.db.port | quote }}
  APP_DB_DATABASE: {{ .Values.app.db.database | quote }}
  APP_DB_VERSION: {{ .Values.app.db.version | quote }}
  APP_OPENPLATFORM_SEARCH_LIMIT: {{ .Values.app.openplatform.search_limit | quote }}
  APP_REDIS_SERVER: {{ .Values.app.redis.server | quote }}
  APP_REDIS_PORT: {{ .Values.app.redis.port | quote }}
  APP_REDIS_CACHE_SERVER: {{ .Values.app.redis.server | quote }}
  APP_REDIS_CACHE_PORT: {{ .Values.app.redis.port | quote }}
  APP_REDIS_CACHE_DB: {{ .Values.app.redis.cache_db | quote }}
  APP_REDIS_CACHE_PREFIX: {{ .Values.app.redis.prefix | quote }}
  APP_REDIS_LOCK_SERVER: {{ .Values.app.redis.server | quote }}
  APP_REDIS_LOCK_PORT: {{ .Values.app.redis.port | quote }}
  APP_REDIS_LOCK_DB: {{ .Values.app.redis.lock_db | quote }}
  APP_METRICS_HOST: {{ .Values.app.redis.server | quote }}
  APP_METRICS_PORT: {{ .Values.app.redis.port | quote }}
  APP_INDEXING_URL: {{ .Values.app.indexing.url | quote }}
  APP_HAS_COVER_SERVICE_URL: {{ .Values.app.has_covere.url | quote }}
  APP_AMQP_SERVER: {{ .Values.app.amqp.server | quote }}
  APP_AMQP_PORT: {{ .Values.app.amqp.port | quote }}
  APP_SUPERVISOR_WORKERS: {{ .Values.app.supervisor.workers | quote }}
  APP_SUPERVISOR_TIME_LIMIT: {{ .Values.app.supervisor.time_limit | quote }}
  APP_SUPERVISOR_QUEUES: {{ join " " .Values.app.supervisor.queues | quote }}
  APP_NO_HITS_TTL: {{ mul .Values.app.no_hits_ttl 1000 | quote }}
  PHP_MEMORY_LIMIT: {{ .Values.app.php.memory_limit | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  2;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections 1024;
      multi_accept on;
    }

    http {
      open_file_cache max=10000 inactive=5m;
      open_file_cache_valid 5m;
      open_file_cache_min_uses 5;
      open_file_cache_errors off;

      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 15 15;
      types_hash_max_size 2048;

      server_tokens off;

      gzip  on;
      gzip_disable "msie6";
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_buffers 16 8k;
      gzip_http_version 1.0;
      gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;

      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

      access_log /var/log/nginx/access.log main;

      include /etc/nginx/conf.d/*.conf;
    }
  default.conf: |
    server {
      listen 80;
      server_name localhost;
      root /var/www/html/public;

      location / {
          add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

          # try to serve file directly, fallback to index.php
          try_files $uri /index.php$is_args$args;
      }

      location = /robots.txt {
         add_header Content-Type text/plain;
         add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
         return 200 "User-agent: *\nDisallow: /\n";
      }

      location ~ ^/index\.php(/|$) {
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_split_path_info ^(.+\.php)(/.*)$;
          include fastcgi_params;

          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param DOCUMENT_ROOT $document_root;

          internal;
      }

      # return 404 for all other php files not matching the front controller
      # this prevents access to other php files you don't want to be accessible.
      location ~ \.php$ {
          return 404;
      }

      error_log /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
    }
