{{- if eq .Values.env "prod" }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  APP_SECRET: ''
  APP_OPENPLATFORM_ID: ''
  APP_OPENPLATFORM_SECRET: ''
  APP_OPENPLATFORM_AGENCY: ''
  APP_DATAWELL_VENDOR_USER: ''
  APP_DATAWELL_VENDOR_PASSWORD: ''
  APP_CLOUDINARY_ID: ''
  APP_CLOUDINARY_SECRET: ''
  APP_CLOUDINARY_DOMAIN: ''
  APP_DB_USERNAME: ''
  APP_DB_PASSWORD: ''
  APP_THEMOVIEDATABASE_APIKEY: ''
  APP_FORSIDERDK_USER: ''
  APP_FORSIDERDK_PASSWORD: ''
  APP_FORSIDERDK_SUBFOLDERS: ''
  APP_AMQP_USERNAME: ''
  APP_AMQP_PASSWORD: ''
{{- end }}

{{- if eq .Values.env "stg" }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  APP_SECRET: ''
  APP_OPENPLATFORM_ID: ''
  APP_OPENPLATFORM_SECRET: ''
  APP_OPENPLATFORM_AGENCY: ''
  APP_DATAWELL_VENDOR_USER: ''
  APP_DATAWELL_VENDOR_PASSWORD: ''
  APP_CLOUDINARY_ID: ''
  APP_CLOUDINARY_SECRET: ''
  APP_CLOUDINARY_DOMAIN: ''
  APP_DB_USERNAME: ''
  APP_DB_PASSWORD: ''
  APP_THEMOVIEDATABASE_APIKEY: ''
  APP_FORSIDERDK_USER: ''
  APP_FORSIDERDK_PASSWORD: ''
  APP_AMQP_USERNAME: ''
  APP_AMQP_PASSWORD: ''
{{- end }}




