# Import settings from 'prod' to match that env.
imports:
    - { resource: '../prod/' }

# Overwrite prod cache settings. Redis not available when building on Github.
framework:
    cache:
        system: cache.adapter.system
        app: cache.adapter.filesystem

        pools:
            # Creates a "no.hits.single.cover.cache" service
            no.hits.single.cover.cache:
                adapter: cache.adapter.filesystem