# Default values for cover-service-importers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: "prod"

# At 01:00 on every day-of-week from Monday through Saturday.
cron:
  runAt: "0 1 * * 1-6"
  successfulLimit: 3
  failedLimit: 1
  startingDeadlineSeconds: 300

# The number of days to preform updates to existing covers for the selected vendor.
days_ago: 180

app:
  image:
    version: latest
    imagePullPolicy: IfNotPresent
  indexing:
    url: "http://es-elasticsearch-coordinating-only.cover-service.svc.cluster.local:9200"
  has_cover:
    enabled: false
    url: "https://ddfhascover.dbc.dk/api/v1/events"
  redis:
    server: "redis-master.cover-service.svc.cluster.local"
    prefix: "DDBCoverImporters"
    port: "6379"
    cache_db: "11"
    lock_db: "2"
  amqp:
    server: "mq-rabbitmq.cover-service.svc.cluster.local"
    port: "5672"
  php:
    memory_limit: "512M"
  db:
    server: "k8s-ddf-prod.mariadb.database.azure.com"
    port: "3306"
    database: "cover-service"
    version: "mariadb-10.6.7"
  vendor:
    forsiderdk_subfolders: '["business", "business2", "culture", "economics", "hospitality", "industries", "law", "literature2", "medicine", "politics", "technology"]'
