# Default values for cover-service-importers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: "prod"

app:
  image:
    version: latest
    imagePullPolicy: IfNotPresent
  indexing:
    url: "http://es-elasticsearch.cover-service.svc.cluster.local:9200"
  has_cover:
    enabled: false
    url: "https://ddfhascover.dbc.dk/api/v1/events"
  no_hits_ttl: 3600
  redis:
    server: "redis-master.cover-service.svc.cluster.local"
    prefix: "DDBCoverImporters"
    port: "6379"
    cache_db: "11"
    lock_db: "2"
  openplatform:
    search_limit: "100"
  amqp:
    server: "mq-rabbitmq.cover-service.svc.cluster.local"
    port: "5672"
  supervisor:
    workers: 8
    time_limit: 900
    queues:
      - async_priority_high
      - async_priority_normal
      - async_priority_low
      - async_no_hit
  vendor:
    forsiderdk:
      enabled: false
      subfolders: '["business", "business2", "culture", "economics", "hospitality", "industries", "law", "literature2", "medicine", "politics", "technology"]'
  php:
    memory_limit: "512M"
  db:
    server: "k8s-ddf-prod.mariadb.database.azure.com"
    port: "3306"
    database: "cover-service"
    version: "mariadb-10.6.7"

nginx:
  image:
    version: 1.23-alpine
    imagePullPolicy: IfNotPresent
