---
on:
  push:
    branch:
      - release
name: Release (stg)

# Environment variables available to all jobs and steps in this workflow
env:
  ORG_NAME: danskernesdigitalebibliotek
  NAMESPACE: cover-service
  APP_VERSION: ${{ github.event.ref }}
  
jobs:
  build:
    name: Staging deploy
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/release') && !github.event.deleted
    steps:
      - uses: actions/checkout@master
      - name: Login to github package registry
        run: docker login docker.pkg.github.com -u publisher -p "${{ secrets.GITHUB_TOKEN }}"

      - name: Build CoverService imports image
        run: docker build --build-arg APP_VERSION=${{ env.APP_VERSION }} --tag="docker.pkg.github.com/${{ env.ORG_NAME }}/ddb-cover-service-importers/cover-service-importers:latest" --file="infrastructure/docker/cover-service-importers/Dockerfile" .

      - name: Build CoverService jobs image
        run: docker build --build-arg APP_VERSION=${{ env.APP_VERSION }} --tag="docker.pkg.github.com/${{ env.ORG_NAME }}/ddb-cover-service/cover-service-jobs:latest" --file="infrastructure/docker/cover-service-jobs/Dockerfile" .

      - name: Push CoverService importers image
        run: docker push docker.pkg.github.com/${{ env.ORG_NAME }}/ddb-cover-service-importers/cover-service-importers:latest

      - name: Push CoverService jobs image
        run: docker push docker.pkg.github.com/${{ env.ORG_NAME }}/ddb-cover-service/cover-service-jobs:latest
